# cron kickstart
# trigger refresh
name: Ejecutar boletin_scraper.py 2 veces por día

on:
  schedule:
    - cron: "30 12 * * *"   # 09:30 hora Argentina
    - cron: "0 18 * * *"    # 15:00 hora Argentina
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Firefox y geckodriver manualmente
        run: |
          mkdir -p $HOME/firefox
          wget -O firefox.tar.xz "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=es-AR"
          tar -xf firefox.tar.xz -C $HOME/firefox --strip-components=1
          echo "$HOME/firefox" >> $GITHUB_PATH

          GECKODRIVER_VERSION=0.36.0
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz"
          tar -xzf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin

      - name: Configurar Python y dependencias
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar librerías Python
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Crear archivo de variables
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
          echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env

      - name: Ejecutar el script
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python boletin_scraper.py

      - name: Enviar notificación por correo
        if: always()
        run: |
          STATUS="✅ Ejecución exitosa"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="❌ Ejecución con errores"
          fi

          echo "[$(date +"%Y-%m-%d %H:%M")] $STATUS" >> ejecuciones.log

          echo -e "Asunto: Estado del scraping Boletín\n\n$STATUS\nGitHub Actions: https://github.com/${{ github.repository }}/actions" | \
          curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd \
            --mail-from "${{ secrets.SMTP_USER }}" \
            --mail-rcpt "${{ secrets.EMAIL_TO }}" \
            --user "${{ secrets.SMTP_USER }}:${{ secrets.SMTP_PASS }}" \
            -T -

      - name: Subir log a Dropbox
        if: always()
        run: |
          pip install dropbox
          python subir_log_dropbox.py
